services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - main
#    environment:
#      - DATABASE_URL=postgres://postgres:6464@postgres:5432/prod?sslmode=disable
#      - RedisHost=redis
#      - RedisPort=6379
#      - RedisPassword=

networks:
  main:
    external: true
    name: Main
