services:
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6464
      POSTGRES_DB: prod
      POSTGRES_INITDB_ARGS: "--max-connections=150"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis
    ports:
      - "6379:6379"

  auth:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:6464@postgres:5432/prod?sslmode=disable
      - RedisHost=redis
      - RedisPort=6379
      - RedisPassword=

volumes:
  postgres_data:
